### PR TITLE
Optimizing the PokemonDatabase

### PR DESCRIPTION
**Pull request by joseka1234**
## Status

IN DEVELOPMENT: Don't merge yet. You are developing on the branch, in response to reviewer comments

## Description

I made this changes in the PokemonDatabase script:

* I've changed the function to get the experience per level. I replace the accesses to the memory (acces to the arrays to get the number) with functions with complexity O(1) so, in a first instance, the game should be faster.

* I've changed the array of PokemonData to a dictionary. With that change we can access the data of the pokemon with complexity O(1) instead of the old one with complexity O(n) so the game should be faster too.

* Now, the dictionary is filled with the previous array but I need to pass all the data to the dictionary to avoid the extra loop and double memory usage.

## Testing

You can enter to a combat but, the best way to prove this code is to make a brute force test with a huge number of accesses to the code.

## Concerns, notes, etc.
I made the change so you don't need to change anything more.

### CODE REVIEW

**Comment by cataclys** [comment]
Stock the data in a real Database or in a NoSQL Database like MongoDB

**Comment by joseka1234** [comment]
I think that I've seen a SQL file with Pokemon data in the Discord.
But change the current system involves into a change in some scripts to access the info and forces the user to have an internet connection.
Another option could be fill all the info in the script with the database once, instead of insert all the data by hand.

**Comment by cataclys** [comment]
Yes it was i have found, but if you don't want SQL connection you can put a file with the data or a Json file

**Comment by GMR516** [comment]
We can make it export a database upon first launch for fast loading. Longer initial set up time, but worth it for an SQL database.

**Comment by herbertmilhomme** [comment]
I thought about a dictionary, but think an Array works best -- for sure an enum is the best of both worlds. If you spell a value wrong in the dictionary, nothing works. There's no way to confirm spelling or remember all the values. an Enum will automatically tell you which value you're loading and list all of them with a reasonable use of the `/// <summary>` telling you what each value leads to. 

Can we close this?...

**Pull request closed without merging**
