### PR TITLE
Create .gitattributes

### PR DESCRIPTION
**Pull request by herbertmilhomme**
Ran into an LFS error on my fork because the main/source repo did not share an option for users to contribute LFS data. Hoping by adding this file, it'll remove the restriction allowing me to push to my own fork without needing to disconnect from source (create a new repo under profile).

Only added the basics of basics, for Unity compatibility. Nothing to break or screw-up anyone's repo.

## Status

- [ ] **Ready**
- [x] **In development** 
- [ ] **Hold**

### CODE REVIEW

**Comment by GMR516** [comment]
Not a problem. Merged.

**Comment by herbertmilhomme** [comment]
Maybe might have to revert this change from the repo, until i can resolve the issue on my end. Cause this did not seem to help me with my issues. I'm looking into more alternative solutions, and hopefully, i'll circle-back to before the problem occurred.

**Comment by GMR516** [comment]
The changes are not a problem for now. Just overwrite them when you come across the solution.

**Comment by herbertmilhomme** [comment]
Solve one problem and another pops-up.
image

I'm able to submit to my repository now!

So, it turns out, you dont need those LFS attributes in your repo. so we can delete that commit. The other attributes might still be helpful. Though it really isnt that big of a deal. 

New problem is, apparently, my build tester cant locate the files in my repository anymore... i'm so confused...

**Comment by GMR516** [comment]
I'm fine with leaving the attributes for now. Like stated, just clean up what you think needs to be done and submit your new version when you have all the bugs worked out.

**Pull request merged**
